---
- name: Testing andrewrothstein.grafana
  hosts: all
  vars:
    grafana_ver: 10.3.1
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'grafana server -v'
      ansible.builtin.command: /usr/local/grafana/bin/grafana server -v
      changed_when: false
      register: grafana_test_output
    - name: Output of 'grafana server -v'
      ansible.builtin.debug:
        msg: '{{ grafana_test_output.stdout }}'
