---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/grafana/bin/grafana server -v
      register: grafana_test_output
    - name: grafana server -v
      debug:
        msg: '{{ grafana_test_output.stdout }}'
