---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Check for installation at {{ grafana_install_dir }}
  become: true
  ansible.builtin.stat:
    path: '{{ grafana_install_dir }}'
  changed_when: false
  register: grafana_binary

- name: Downloading and installing grafana
  when: not grafana_binary.stat.exists
  block:
    - name: Downloading {{ grafana_tgz_url }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ grafana_tgz_url }}'
        dest: '{{ grafana_tmp_tgz }}'
        checksum: '{{ grafana_checksum }}'
        mode: '644'
    - name: Unarchiving {{ grafana_tmp_tgz }} to {{ grafana_parent_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        src: '{{ grafana_tmp_tgz }}'
        dest: '{{ grafana_parent_install_dir }}'
        creates: '{{ grafana_install_dir }}'
  always:
    - name: Rm -f {{ grafana_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ grafana_tmp_tgz }}'
        state: absent

- name: Linking {{ grafana_link_dir }} to {{ grafana_install_dir }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ grafana_install_dir }}'
    dest: '{{ grafana_link_dir }}'
    state: link

- name: Add to login shell path...
  become: true
  become_user: root
  with_items:
    - f: grafana.sh
      d: /etc/profile.d
  ansible.builtin.template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m | default("0644") }}'
